### ISSUE TITLE
Once downloaded, the same tag cannot be downloaded again.

### ISSUE THREAD

**Issue by r2ten-catuncle** [Official-Husko/NN-Downloader#18]
![image](https://github.com/Official-Husko/NN-Downloader/assets/105350332/5d5001e8-e8fb-4e99-a144-ff0f83df4de8)
After downloading a tag, after moving the folder out, I cannot download the same tag again.
I don't know if there is something wrong with my operation

**Comment by Official-Husko** [comment]
Well the tool has a feature to remember what it downloaded so that when you want to get the new images of that certain tag(s) you can without having to go through duplicates and wasted drive space.

If you don't want that you can disable it in the config by setting `"oneTimeDownload": true,` to `"oneTimeDownload": false,`.
Alternatively if you want to keep this feature for now but start over you can just delete the appropriate database file located in the same folder as the program itself. Look for a db folder and in there delete the e621.db file.


If this resolved your issue please close it. Otherwise feel free to ask further questions.

**Comment by r2ten-catuncle** [comment]
After deleting the E621 file in the db folder, I can download it again.
Changing "oneTimeDownload" of the .json file to false will cause the program to crash and exit.

**Comment by Official-Husko** [comment]
> After deleting the E621 file in the db folder, I can download it again. Changing "oneTimeDownload" of the .json file to false will cause the program to crash and exit.

It crashes? Well fuck me sideways. Hotfix time then. Thank you for reporting that.
