### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by goatzyboi** [Official-Husko/NN-Downloader#36]
heyy im kinda new at github and i dont actually know how to download it correctly (or at least how to execute it)

at first ive tried to click on "windows donwload"
but it ends creating and downloader wich just keeps creating 2 empty folders and one text (config)
and ive even tried to download it with linux but i wasnt able to to found an applicantion to actually start the nn-donwloader, since ive tried to open almost everysingle archive in that folder...

im pretty sure that im just being really stupid on trying to find how to use it but plz, help me TwT

btw excuse my bad english, im still learning it

**Comment by Official-Husko** [comment]
Greetings! Which platform would you prefer to use specifically? for windows just download the exe. The first time it is launched it creates a few required items after which it will close. Configure it and then launch it again to use it as needed. For linux you should be able to run it instantly from what i know since python is pre-installed most of the time if not google your way around on how to install python. Then open the folder where you extracted the source code to and enter "pip install -r requirements.txt" and then "python main.py" which should open it for you.

**Comment by Official-Husko** [comment]
@goatzyboi Have you been able to resolve your issue?

**Comment by Official-Husko** [comment]
Closing this issue due to a lack of further feedback. If you think this is a mistake you may comment on this issue again to reopen it.
